# This file contains various configuration settings for Rubocop. Basically, these are specific problems that Rubocop *would* find, but I'm telling it not to worry about them. There are some coding "problems" which are really just Rubocop's "preferences", and I don't care for them.

Style/Encoding:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/StringLiterals:
  Enabled: false